services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  redis:
    extends:
      file: docker-compose.yml
      service: redis
  fixture-music:
    extends:
      file: docker-compose.yml
      service: fixture-music
  navidrome:
    extends:
      file: docker-compose.yml
      service: navidrome
  recommendation-api:
    extends:
      file: docker-compose.yml
      service: recommendation-api
  event-api:
    extends:
      file: docker-compose.yml
      service: event-api
  catalog-sync-worker:
    extends:
      file: docker-compose.yml
      service: catalog-sync-worker
  frontend-web:
    extends:
      file: docker-compose.yml
      service: frontend-web
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
  object-storage:
    extends:
      file: docker-compose.vm2.yml
      service: object-storage
  mlflow:
    extends:
      file: docker-compose.vm2.yml
      service: mlflow
  retraining-runner:
    extends:
      file: docker-compose.vm2.yml
      service: retraining-runner
  promotion-gate:
    extends:
      file: docker-compose.vm2.yml
      service: promotion-gate

volumes:
  spotiboys-postgres:
  spotiboys-navidrome-data:
  spotiboys-fixture-music:
  spotiboys-object-storage:
  spotiboys-mlflow:
