name: "gru_ranker"
platform: "onnxruntime_onnx"
max_batch_size: 32
input [
  { name: "item_embs",       data_type: TYPE_FP32,  dims: [ 20, 128 ] },
  { name: "labels",          data_type: TYPE_INT64,  dims: [ 20 ] },
  { name: "u_long",          data_type: TYPE_FP32,  dims: [ 128 ] },
  { name: "candidate_embs",  data_type: TYPE_FP32,  dims: [ 200, 128 ] },
  { name: "cross_features",  data_type: TYPE_FP32,  dims: [ 200, 3 ] }
]
output [
  { name: "scores",          data_type: TYPE_FP32,  dims: [ 200 ] }
]
dynamic_batching {
  preferred_batch_size: [ 4, 8, 16 ]
  max_queue_delay_microseconds: 5000
}
