name: "pann"
platform: "onnxruntime_onnx"
max_batch_size: 32
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
output [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [ 2048 ]
  }
]
dynamic_batching {
  preferred_batch_size: [ 4, 8, 16, 32 ]
  max_queue_delay_microseconds: 1000
}
